Feature/interactive menu
vovek/reactive-adidas-shop pull request #10
Opened 2017-05-23 19:45 UTC by vovek

2017-05-24 08:29 UTC, imevro requested changes

2017-05-24 08:29 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +import Item, { Link } from './Item';
Item глупое название

2017-05-24 08:29 UTC, evgenyrodionov commented on src/Sidebar/Menu/index.jsx
> +      <Link to="/" isSubLink href="">Shoes</Link>
Зачем проп isSubLink? Почему href вместе с to?

2017-05-24 08:54 UTC, vovek commented on src/Sidebar/Menu/index.jsx
> +      <Link to="/" isSubLink href="">Shoes</Link>
Осталось от прошлой реализации, уберу. Спс

2017-05-24 09:01 UTC, vovek commented on src/Sidebar/Menu/index.jsx
> +import Item, { Link } from './Item';
Посоветуешь что получше?)

2017-05-24 21:08 UTC, imevro requested changes

2017-05-24 21:08 UTC, evgenyrodionov commented on src/Sidebar/Navigation/Menu.jsx
> +      isOpened: !this.state.isOpened,
нет, в журналист сказано об этом

2017-05-24 21:08 UTC, evgenyrodionov commented on src/Sidebar/Navigation/index.jsx
> +/*  import { MainMenu, SubMenu, Link } from './styled-components';*/
убирай мусор

2017-05-25 09:29 UTC, imevro requested changes

2017-05-25 09:29 UTC, evgenyrodionov commented on src/Sidebar/Navigation/Menu.jsx
> +export default class Item extends React.Component {
Item тупой нейминг

2017-05-25 09:29 UTC, evgenyrodionov commented on src/Sidebar/Navigation/Menu.jsx
> +  }
Между методами класса делай отступ в одну пустую строку

2017-05-25 16:50 UTC, imevro approved these changes

2017-05-25 16:50 UTC, merged