Feature/color switcher
vovek/reactive-adidas-shop pull request #14
Opened 2017-05-26 22:34 UTC by vovek

пиздец, сделал сутки назад и забыл создать PR

2017-05-26 22:48 UTC, vovek commented
Коммит выше должен был быть не в этой ветке. Но тк он совсем маленький - просьба оставить.

2017-05-27 08:06 UTC, imevro requested changes

2017-05-27 08:06 UTC, evgenyrodionov commented on src/Products/Show/Meta/Right/ColorSwitcher.jsx
> +      key={color.toString()}
Зачем тустринг?

2017-05-27 08:06 UTC, evgenyrodionov commented on src/Products/Show/Meta/Right/ColorSwitcher.jsx
> +  const switchers = props.colors.map(color => (
Убирай константу, рендерь прямо там где используешь мап

2017-05-27 08:06 UTC, evgenyrodionov commented on src/Products/Show/index.jsx
> +    this.state = { currentColor: colors[0] };
Храни в стейте индекс, а не значение

2017-05-27 08:53 UTC, imevro requested changes

2017-05-27 08:53 UTC, evgenyrodionov commented on src/Products/Show/Meta/index.jsx
> +export default ({ colors, colorIndex, handleChangeColor }) => (
Передавай сразу color, смысл массив с индексом

2017-05-27 09:15 UTC, merged